# for local testing
# main text of home
name: Benson Lin
bio: 'A Man who concentrates on software development '

# if it's an external image, update below for true
external-image: false
picture: '/assets/images/profile.png'

url: http://localhost:4000
# url: http://blog.bensonlin.me
# your url: http://zebinlin.github.io http://localhost:4000

permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-MYANALYTICS'

# if you don't want comments in your posts, set to false
disqus: zebinlin

# if you don't have any of social below, comment the line
## facebook: myfacebook
## twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
## youtube: myyoutube
## spotify: myspotify
github: benson-lin
## medium: medium
email: l096101803@qq.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
paginate: 10
paginate_path: "post/:num/"

# if you don't need projects, comment the *projects* configs below
project: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

blog-branch: '/post'
project-branch: '/project'
about-branch: '/about'
# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, Rakefile, screen-shot.png, travis.sh]
